mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            
            jwt:
                secret: '%env(MERCURE_JWT_SECRET)%'
                value: '%env(MERCURE_JWT_TOKEN)%'


